// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bwselexvaozmyfboxlps.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3c2VsZXh2YW96bXlmYm94bHBzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0MjY2NjcsImV4cCI6MjA3NDAwMjY2N30.OH65Eksqa_D3U6o3XEaI06MwEXl4s1RZjAaTIdRn78c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});